DROP EVENT IF EXISTS PTS_EXPORT_SCHEDULE
$$
SET GLOBAL event_scheduler="ON"
$$
CREATE EVENT IF NOT EXISTS PTS_EXPORT_SCHEDULE
ON SCHEDULE EVERY 5 SECOND
COMMENT 'EXPORT DATA TABLES EVERY 5 SECOND'
 DO
   BEGIN
-- CALL PROCEDURE TO EXPORT DATA AND PASSING TYPE IN PARAMETER --------
      CALL  EXPORT_TOPIC();
      CALL  EXPORT_SPRINT();
      CALL  EXPORT_DAILY_SCRUM();
      CALL  EXPORT_DS_PARTICIPANT();
      CALL  EXPORT_USER_STORY();
   END;
$$