CREATE TABLE `pts_ticket_import` (
  `ticket_import_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `ticket_id` bigint(20) DEFAULT NULL,
  `state` bigint(20) DEFAULT NULL,
  `responsible_id` bigint(20) DEFAULT NULL,
  `editor_id` bigint(20) DEFAULT NULL,
  `release_id` bigint(20) DEFAULT NULL,
  `product_id` bigint(20) DEFAULT NULL,
  `matrix_id` bigint(20) DEFAULT NULL,
  `fl1` bigint(20) DEFAULT NULL,
  `fl2` bigint(20) DEFAULT NULL,
  `fl3` bigint(20) DEFAULT NULL,
  `short_description` varchar(250) CHARACTER SET utf8 DEFAULT NULL,
  `long_description` text CHARACTER SET utf8,
  `solution_description` text CHARACTER SET utf8,
  `assignment` varchar(50) CHARACTER SET utf8 DEFAULT NULL,
  `file_name_1` varchar(100) CHARACTER SET utf8 DEFAULT NULL,
  `file_name_2` varchar(100) CHARACTER SET utf8 DEFAULT NULL,
  `file_name_3` varchar(100) CHARACTER SET utf8 DEFAULT NULL,
  `os_name` varchar(100) CHARACTER SET utf8 DEFAULT NULL,
  `environment` varchar(100) CHARACTER SET utf8 DEFAULT NULL,
  `server` varchar(100) CHARACTER SET utf8 DEFAULT NULL,
  `ticket_database` varchar(100) CHARACTER SET utf8 DEFAULT NULL,
  `priority` bigint(20) DEFAULT NULL,
  `urgency` bigint(20) DEFAULT NULL,
  `comment` text CHARACTER SET utf8,
  `ap_id` bigint(20) DEFAULT NULL,
  `ap_name` varchar(100) CHARACTER SET utf8 DEFAULT NULL,
  `ap_tel` varchar(100) CHARACTER SET utf8 DEFAULT NULL,
  `ap_bank` varchar(100) CHARACTER SET utf8 DEFAULT NULL,
  `company` varchar(500) DEFAULT NULL,
  `responsible_pl` bigint(20) DEFAULT NULL,
  `lock_date` datetime DEFAULT NULL,
  `is_chrq` bit(1) DEFAULT NULL,
  `customer_id` bigint(20) DEFAULT NULL,
  `cust_user_id` bigint(20) DEFAULT NULL,
  `sent_back_by` bigint(20) DEFAULT NULL,
  `mail_date` datetime DEFAULT NULL,
  `kunde_ref` varchar(100) CHARACTER SET utf8 DEFAULT NULL,
  `service_level_info` text CHARACTER SET utf8,
  `target_date` datetime DEFAULT NULL,
  `remark` text CHARACTER SET utf8,
  `last_updated_field` text CHARACTER SET utf8,
  `production_release_id` bigint(20) DEFAULT NULL,
  `test_release_id` bigint(20) DEFAULT NULL,
  `country` varchar(100) CHARACTER SET utf8 DEFAULT NULL,
  `ts_insert` datetime DEFAULT NULL,
  `ts_update` datetime DEFAULT NULL,
  `email` varchar(128) CHARACTER SET utf8 DEFAULT NULL,
  `editor` varchar(100) CHARACTER SET utf8 DEFAULT NULL,
  `type` bigint(20) DEFAULT NULL,
  `creator` varchar(100) CHARACTER SET utf8 DEFAULT NULL,
  `plan_release_id` bigint(20) DEFAULT NULL,
  `effort` decimal(31,15) DEFAULT NULL,
  `progress` bigint(20) DEFAULT NULL,
  `deadline` datetime DEFAULT NULL,
  `country_id` bigint(20) DEFAULT NULL,
  `parent_ticket_id` bigint(20) DEFAULT NULL,
  `estimated_effort` decimal(31,15) DEFAULT NULL,
  `project` varchar(100) CHARACTER SET utf8 DEFAULT NULL,
  `amount_1` decimal(31,15) DEFAULT NULL,
  `amount_2` decimal(31,15) DEFAULT NULL,
  `amount_3` decimal(31,15) DEFAULT NULL,
  `amount_4` decimal(31,15) DEFAULT NULL,
  `amount_5` decimal(31,15) DEFAULT NULL,
  `text_m_1` varchar(250) DEFAULT NULL,
  `text_m_2` varchar(250) DEFAULT NULL,
  `text_m_3` varchar(250) DEFAULT NULL,
  `text_s_1` varchar(150) DEFAULT NULL,
  `text_s_2` varchar(150) DEFAULT NULL,
  `text_l_1` text,
  `text_xl_1` longtext,
  `date_time_1` datetime DEFAULT NULL,
  `date_time_2` datetime DEFAULT NULL,
  `date_time_3` datetime DEFAULT NULL,
  `info_msg` varchar(500) DEFAULT NULL,
  `last_chat_msg` varchar(250) DEFAULT NULL,
  PRIMARY KEY (`ticket_import_id`)
) ENGINE=MyISAM AUTO_INCREMENT=1000 DEFAULT CHARSET=latin1;
$$

